### ISSUE TITLE
Creating Keys with File Name Prefix and Single Bucket Access

### ISSUE THREAD

**Issue by petermierau** [Backblaze/b2-sdk-java#105]
I'm having trouble figuring out how to create an account key with filename prefix and single bucket access. I've looked thru the examples, where did I miss it?

**Comment by bwbeach** [comment]
A command like this will do it:

```
b2 create-key --duration 86400 --bucket my-bucket --namePrefix photos/ test-key readFiles,writeFiles
```

**Comment by petermierau** [comment]
Hey!

So that’s not possible to do with the JavaSDK? Or it is and I need to pass in parameters I’m not seeing?

When I build a key I can select permissions but I can’t seem to do anything else. I’m missing something obviously.

**Comment by certainmagic** [comment]
Hi Peter --

Ooops! Although he's awesome in any language, BrianB usually responds to the CLI questions.  :)

You should be able to do something like this:
```
final B2StorageClient b2StorageClient = ids.getB2StorageClient();
final String bucketId = "bucket-id";
final Set<String> capabilities = new TreeSet<>();
capabilities.add(B2Capabilities.READ_FILES);
capabilities.add(B2Capabilities.WRITE_FILES);
final B2CreateKeyRequest request = B2CreateKeyRequest.builder(capabilities,"key-name")
        .setBucketId(bucketId)
        .setNamePrefix("/only/with/this/prefix/")
        .setValidDurationInSeconds(86400L)
        .build();
b2StorageClient.createKey(request);
```

ttfn,
ab

**Comment by petermierau** [comment]
Thank you!!!

That’s exactly what I was looking for. Cheers!

**Comment by certainmagic** [comment]
Great!  Glad to hear it.  :)
