### ISSUE TITLE
#include freeglut/freeglut.h must be changed to #include <GL/freeglut.h>

### ISSUE THREAD

**Issue by ianmanifacier** [Backblaze/b2-sdk-java#122]
Hi,

I down loaded the the C++ files.
I could not compile because one library was missing "freeglut".

After installing using the vcpkg manager it the problem remained.

There seem to have been a folder name change from "freeglut" to "GL"

Here is my fix of the B2dJsonImage_OpenGL.h:

#ifdef __APPLE__
	#include <GLUT/glut.h>
#else
    #include <GL/freeglut.h>
   //#include "freeglut/freeglut.h"
#endif

My code now compiles fine

Best

**Comment by certainmagic** [comment]
Hi ianmanifacier --

I suspect you picked the wrong project when reporting this issue.  There's no C++ or GL in b2-sdk-java.  :)

I'm going to close this ticket and hope that you find the right project.

good luck!

**Comment by ianmanifacier** [comment]
Hi,
Yes, apparently. Sorry about that
Have a good day
