### ISSUE TITLE
add methods for uploading parts

### ISSUE THREAD

**Issue by z0mb1ek** [Backblaze/b2-sdk-java#128]
Hi. I see comment:

> When possible you should seriously consider using uploadLargeFile() instead of reimplementing that logic.  If there's a reason you can't use those methods, let us know.  Perhaps we can improve things together to meet your needs.

I want to create backend for uploading files with Tus(tus.io) 
It would be great sdk has methods for uploads part with refreshing authorisation logic inside

**Comment by certainmagic** [comment]
I think this is  actually a vote for #96.   Do you agree?

**Comment by z0mb1ek** [comment]
yes
