### ISSUE TITLE
CORS not supported

### ISSUE THREAD

**Issue by mianor64** [Backblaze/b2-sdk-java#15]
Hi, 

I was trying to replace S3 with BackBlaze but I hit a major issue with your sdk & solution.
It looks like CORS is not supported so I am currently unable to upload files to your servers directly from a browser.
https://help.backblaze.com/hc/en-us/articles/114094192774-Does-B2-have-CORS-headers-support-

It will be easy on your side to enable CORS but as long as it's disabled I can't use Backblaze for my project.

**Comment by certainmagic** [comment]
Yep.  We don't support CORS configurations yet.  We are working on it now
for downloads.  We have not yet scheduled adding it for uploads.

thanks,
ab

**Comment by certainmagic** [comment]
FYI, documentation about our CORS rules and using them for downloads is now online:

   https://www.backblaze.com/b2/docs/cors_rules.html

Support for using them for downloads is "coming soon".
Support for uploads is still not scheduled.

**Comment by certainmagic** [comment]
Support for CORS for downloads is live.

**Comment by ricky11** [comment]
How about for listing buckets?

**Comment by nilayp** [comment]
Ricky - thanks for the feedback! We are considering adding additional APIs to our CORS support once our application keys functionality is in place. This should happen in the next couple months. Details on that are here, we'd love your feedback: https://www.backblaze.com/b2/docs/application_keys.html. 

Out of curiosity - can you explain your use case? I'd love to understand what you are trying to achieve.

**Comment by ricky11** [comment]
Hi

Thanks for your reply

Im a little confused as your website shows a settings for my bucket called “CORS” see below.

[cid:image001.png@01D3B6FC.E3A34BE0]



Which API’S does CORS current support?

Right now from my browser I am trying to use the following :

b2_authorize_account<https://www.backblaze.com/b2/docs/b2_authorize_account.html>
b2_get_upload_url<https://www.backblaze.com/b2/docs/b2_get_upload_url.html>
b2_download_file_by_id<https://www.backblaze.com/b2/docs/b2_download_file_by_id.html>

b2_get_download_authorization<https://www.backblaze.com/b2/docs/b2_get_download_authorization.html>

b2_list_buckets<https://www.backblaze.com/b2/docs/b2_list_buckets.html>
b2_upload_file<https://www.backblaze.com/b2/docs/b2_upload_file.html>


So if CORS is not currently support for any of the above API operations, what are my options, do I have to do all my API calls from a backend server outside of the browser? Do you support node?

What I am trying to achieve is a dropbox like sharing application for our industry, sign in, upload, download files etc I am using vanilla javascript with a node server.

Sincerely,
Rishi Uttam

Paramount Manufacturing Group Limited

**Comment by nilayp** [comment]
Rishi,

Right now - B2 allows four API calls to be made from within a web browser, provided the [CORS rules](https://www.backblaze.com/b2/docs/cors_rules.html) are setup. These are [b2_upload_file](https://www.backblaze.com/b2/docs/b2_upload_file.html), [b2_upload_part](https://www.backblaze.com/b2/docs/b2_upload_part.html), [b2_download_file_by_name](https://www.backblaze.com/b2/docs/b2_download_file_by_name.html) and [b2_download_file_by_id](https://www.backblaze.com/b2/docs/b2_download_file_by_id.html). 

The rest of the API calls need to be made by your backend server.

We do not have an official node.js SDK, but you can either call the web APIs directly in node, or try the [open source node B2 SDK](https://www.npmjs.com/package/backblaze-b2). While we don't support it ourselves, it does seem to have a budding community and regularly gets updates.

Does that answer your question?

-- Nilay

**Comment by ricky11** [comment]
Hi Nilay

Thanks, yes it does answer my questions, I wasn’t sure as I couldn’t find that out in the documentation, can you please provide that link?
So according to your message below I can download and upload in the browser but I must authorize and obtain the upload url from the server, is that right?

My cors rules are set up to currently allow all access from anywhere.

Thanks, I will look in to the SDK.

Best
Rishi

**Comment by ricky11** [comment]
Hi Nilay

Further to my CORS enquiry,

I have set up CORS on my bucket using the interface on your website which gives me the option to “Share everything with every origin”

Is this sufficient to allow b2_uplaod_file?

Or do I need to add a custom rule?  When adding a custom rule using b2 command line, I am trying to upload my json file but I am not sure of the command syntax, I am trying :

b2  update-bucket --bucketInfo sinosend --corsRules bucket.json

Please help.
Thanks
Rishi

[cid:image001.png@01D3B7DA.53B2D9E0]

Sincerely,
Rishi Uttam

**Comment by ricky11** [comment]
Resend, awaiting support reply.

Sincerely,
Rishi Uttam



From: Rishi Uttam
Sent: Friday, March 9, 2018 7:11 PM
To: Backblaze/b2-sdk-java <reply@reply.github.com>; Backblaze/b2-sdk-java <b2-sdk-java@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [Backblaze/b2-sdk-java] CORS not supported (#15)

Hi Nilay

Further to my CORS enquiry,

I have set up CORS on my bucket using the interface on your website which gives me the option to “Share everything with every origin”

Is this sufficient to allow b2_uplaod_file?

Or do I need to add a custom rule?  When adding a custom rule using b2 command line, I am trying to upload my json file but I am not sure of the command syntax, I am trying :

b2  update-bucket --bucketInfo sinosend --corsRules bucket.json

Please help.
Thanks
Rishi

[cid:image001.png@01D3BAD3.80CC6120]

Sincerely,
Rishi Uttam

**Comment by ricky11** [comment]
Resent, hoping for support reply.

Sincerely,
Rishi Uttam

Paramount Manufacturing Group Limited


From: Rishi Uttam
Sent: Friday, March 9, 2018 9:18 AM
To: Backblaze/b2-sdk-java <reply@reply.github.com>; Backblaze/b2-sdk-java <b2-sdk-java@noreply.github.com>
Subject: RE: [Backblaze/b2-sdk-java] CORS not supported (#15)

Hi Nilay

Thanks, yes it does answer my questions, I wasn’t sure as I couldn’t find that out in the documentation, can you please provide that link?
So according to your message below I can download and upload in the browser but I must authorize and obtain the upload url from the server, is that right?

My cors rules are set up to currently allow all access from anywhere.

Thanks, I will look in to the SDK.

Best
Rishi

**Comment by nilayp** [comment]
Rishi - This is a forum for Java SDK questions. For CORS questions as they pertain to B2, please open a support ticket here: https://help.backblaze.com/hc/en-us/requests/new

I'm going to close this issue
