### ISSUE TITLE
getBucketOrNullByName() results in 401 response of a key is limited to that bucket

### ISSUE THREAD

**Issue by skand888** [Backblaze/b2-sdk-java#151]
This is because this function tries to list all buckets instead of using the `bucketName` option of the `B2ListBucketsRequest`
```java
    default B2Bucket getBucketOrNullByName(String name) throws B2Exception {
        for (B2Bucket bucket : buckets()) {
            if (bucket.getBucketName().equals(name)) {
                return bucket;
            }
        }
        return null;
    }
```
According to B2 documentation: "If you ask for all buckets and your application key is restricted to one bucket, the call is unauthorized."

The workaround is to call `listBuckets()` with the bucket name as an option instead of `getBucketOrNullByName()`.

**Comment by ericjding** [comment]
Fixed in #152
