### ISSUE TITLE
Possible to delete bucket if it is not empty. 

### ISSUE THREAD

**Issue by valenpo** [Backblaze/b2-sdk-java#29]
It will be nice, if API has a possibility to delete bucket if it is not empty. Cause right now we need remove all files in bucket before deletion. 

Thanks

**Comment by certainmagic** [comment]
Hi valenpo --

Would having a method that deletes all files in a bucket meet your needs?

You could then write:
     client.deleteAllFilesInBucket(bucketId);
     client.deleteBucket(bucketId);

If so, would you like to make a pull request to add deleteAllFilesInBucket()?

thanks,
ab

**Comment by certainmagic** [comment]
Thanks, Valentin.  :)
I look forward to seeing your PR.  :)

ttfn,
ab

**Comment by certainmagic** [comment]
Hi Valentin --

I just merged your PR which contained deleteAllFilesInBucket() and it's in master now.  :)

I also added you to the Contributors section of the README.  Thanks for your contribution.  :)

thanks!
ab

**Comment by inetshell** [comment]
Hi @valenpo  and team!
I need to remove all files in a bucket, but I just know python. Could you help me to have a sample of just how to remove all files in a bucket? I'm looking at the code [here](https://github.com/Backblaze/b2-sdk-java/blob/master/samples/src/main/java/com/backblaze/b2/sample/B2Sample.java) but just don't get it :|

**Comment by certainmagic** [comment]
Hi inetshell --

Welcome to the Java SDK.  With Valentin's contribution, you should be able to create a storage client and just call deleteAllFilesInBucket(bucketId).

If you want to write code in Python, checkout the official Python B2 SDK ([b2-sdk-python](https://github.com/Backblaze/b2-sdk-python)).  I believe up-to-date docs are [here](https://b2-sdk-python.readthedocs.io/en/master/).

If you're not interested in writing code, there is also a [command-line tool](https://github.com/Backblaze/B2_Command_Line_Tool) written in python on top of the python SDK.  And plenty of [other integrations](https://www.backblaze.com/b2/integrations.html).

Please let us know if these pointers get you where you're trying to go.  :)

thanks,
ab

**Comment by inetshell** [comment]
I'm trying that, but the bucket have 18million files and it's very slow.

**Comment by eliliam** [comment]
@inetshell I am in the same situation, it would be very nice to have a native way(through sdk, cli, or web) to delete a non-empty bucket. If anyone knows of any faster ways to empty/delete a non-empty bucket, let me know!
