### ISSUE TITLE
get bucket size

### ISSUE THREAD

**Issue by jamieb22** [Backblaze/b2-sdk-java#30]
We need a way to obtain the used size of a bucket.

**Comment by certainmagic** [comment]
Hi Jamie --

As I'm sure you're aware, you can implement something like that using b2_list_file_versions.  Of course, if there are a lot of files, it can be slow (and the API calls can add up), so I understand your desire to have a less expensive alternative.

Please tell me more about your application.  What is your goal with having such an API?  How accurate would you want it to be?  How slow?  What if the answer was an estimate?  What if sometimes the estimate wasn't available at all?

thanks,
ab

**Comment by jamieb22** [comment]
We need the figure for reporting and billing purposes. In our app, we have a requirement to charge per byte / kb stored. It is infeasible to use the  b2_list_file_versions since we are storing millions of blobs. Obviously, the more accurate the better, although, if it must be an estimate then that is better than nothing. Ideally, we want an immediate response. I would imagine that Backblaze would need to maintain a cache containing the cumulative size of all blobs stored for a given bucket. We would obviously prefer the estimate to be always available, but, I suppose we could workaround if the estimate were only available at certain times. In this case, I would expect that you could include a last estimate date along with size estimate, so that we at least know when the estimate was calculated.

**Comment by certainmagic** [comment]
Hi Jamie --

Thank you for telling me more about what you would like.

It sounds like each bucket just has files for just one customer, or the per-bucket totals wouldn't be enough for you.  Do you have more than one customer per account?

thanks,
ab

**Comment by jamieb22** [comment]
We would like per bucket totals. In our system, one customer can have potentially many buckets, although the common case is a one to one relationship. In any case, we know the buckets associated each of our customers, so if we wanted to know total usage of a given customer, we could just sum the result of the get bucket size API call for each bucket.

**Comment by certainmagic** [comment]
Hi Jamie --

As you probably know, the API you're asking for doesn't exist in the underlying B2 service.  I've talked to people here and it's in the list of possible future features, but it isn't scheduled yet.  Once that API gets added to the B2 service, it will be added to b2-sdk-java so that you can access it easily from Java.

In the meantime, I'm going to close this issue.

thanks,
ab
