### ISSUE TITLE
Is it possible iterate files in folder not on bucket.

### ISSUE THREAD

**Issue by valenpo** [Backblaze/b2-sdk-java#39]
I have a bucket "test" and folders there {one, two, three}. Is it possible to iterate all files on folder one?

Thanks!

**Comment by certainmagic** [comment]
Hi Valentin --

Yep!  Take a look at the "prefix" argument to b2_list_file_names [1].

In b2-sdk-java, use something like the following to create your request: 
```
  B2ListFileNamesRequest request = B2ListFileNamesRequest.builder(bucketId)
              .setMaxFileCount(1000)
              .setPrefix("one/")
              .build();
```

You can then pass that request object to a method such as B2StorageClient.fileNames().

Does that do what you want?

thanks,
ab


[1] https://www.backblaze.com/b2/docs/b2_list_file_names.html

**Comment by valenpo** [comment]
@certainmagic thanks! This is exactly I searching. 

thanks,
vp
