### ISSUE TITLE
New "union" support needs to support a "defaultForInvalid".

### ISSUE THREAD

**Issue by certainmagic** [Backblaze/b2-sdk-java#46]
We need a way to designate how to handle an unknown union type.  We want to be sure that clients running with an "old" idea of the allowed union subtypes can still parse json that contains a "new" union subtype.  The clients won't be able to process the new type, but they shouldn't get a parsing error.  Instead, when they look at the type in the field, it should be an instance of the type designated as being for unknown subtypes. 

This fills a similar compatibility need as the @B2Json.defaultForInvalidEnumValue annotation does for enums.

Here are some things I think need to be defined:

  * what do we call this thing?

  * how to mark the special class?
     * with an annotation on the type (similar to @defaultForInvalidEnumValue)?
     * with a special put() on B2JsonUnionTypeMap.Builder? putUnknownTypeHandler()?
     * other?

  * what restrictions are there on that type?
     * presumably there can be at most one type designated this way.
     * what fields is it allowed to have?
        * is it allowed to have any?
        * is it allowed to have any required fields?
        * other?

  * if there isn't one, do we just continue to throw a parse error?  (i'm assuming yes.)

**Comment by bwbeach** [comment]
Unions now support default values that are used when the type is unknown.
