### ISSUE TITLE
verify that URLs that come from the b2 api are on backblaze domains.

### ISSUE THREAD

**Issue by certainmagic** [Backblaze/b2-sdk-java#47]
for instance, there are urls that come back from b2_authorize_account, b2_get_upload_url, etc.  we want to be sure that they're on one of our main domains, such as backblaze[b2].{com,net,xyz}.

**Comment by GreenReaper** [comment]
Maybe not if someone else implemented the b2 API? Or if it was being filtered for an org's purposes.

I think it should trust the return values from the server you set via B2ClientConfig.setMasterUrl(). (Ensuring that your connection to that server is secure is a matter for the transport protocol.)

**Comment by certainmagic** [comment]
Yep.  You'll notice that we haven't been in a hurry to implement this.  If we did this, I think we'd have to make it possible to not have this restriction, but that might not be available to an end-user of a product, so programatic support for accepting a wider set of domains might not be sufficient for end-users.

Just curious, are you, or someone you know, implementing the B2 api?  I'd love to learn more.  :)

**Comment by GreenReaper** [comment]
I fear the truth is more mundane - I stumbled across this while searching for a place to suggest a b2_get_caps or similar for the purpose of integration with our existing [Munin](http://munin-monitoring.org/) monitoring. Writing a script to login with full credentials and [scrape them from the website](https://secure.backblaze.com/b2_caps_alerts.htm) seems like a 
bad ideaa! As I understand it, API suggestions are tracked internally, so I'll file it as a support request.

**Comment by certainmagic** [comment]
Yep.  This project is for supporting existing APIs, not feature requests.
Thanks for directing your request directly at Backblaze instead of just the
java sdk.  :)

thanks,
ab

**Comment by certainmagic** [comment]
I don't think we're gonna ever do this.  Closing.
