### ISSUE TITLE
Passed-in SHA1 is missing from large file

### ISSUE THREAD

**Issue by azell** [Backblaze/b2-sdk-java#50]
Guts of the Java 10 code with 1.4.0:

```
  private void upload(String fileName) throws B2Exception, IOException {
    var file = new File(fileName);
    String sha1;

    try (InputStream in = new FileInputStream(file)) {
      sha1 = B2Sha1.hexSha1OfInputStream(in);
    }

    var request =
        B2UploadFileRequest.builder(
                bucketId,
                fileName,
                B2ContentTypes.B2_AUTO,
                B2FileContentSource.builder(file).setSha1(sha1).build())
            .setListener(listener(fileName))
            .build();

    LOGGER.info("{} -> {}", fileName, sha1);

    var version =
        client.getFilePolicy().shouldBeLargeFile(request.getContentSource().getContentLength())
            ? client.uploadLargeFile(request, executor)
            : client.uploadSmallFile(request);

    LOGGER.info("{} upload completed -> {}", fileName, version);
  }
```

Output is like:

```
18:36:52.015 [main] INFO com.github.test.b2_cloud.Main - test.ts -> e8079d27e0bde7eb92eb14f417cb18bdd7b24d6d
18:36:52.073 [main] INFO com.github.test.b2_cloud.Main - test.ts WAITING_TO_START 0% 1/65
18:36:52.077 [main] INFO com.github.test.b2_cloud.Main - test.ts WAITING_TO_START 0% 2/65
18:36:52.077 [main] INFO com.github.test.b2_cloud.Main - test.ts WAITING_TO_START 0% 3/65
...
19:56:55.910 [b2_cloud-7] INFO com.github.test.b2_cloud.Main - test.ts UPLOADING 100% 63/65
19:56:58.089 [b2_cloud-7] INFO com.github.test.b2_cloud.Main - test.ts SUCCEEDED 100% 63/65
19:56:59.727 [b2_cloud-5] INFO com.github.test.b2_cloud.Main - test.ts UPLOADING 100% 64/65
19:57:01.392 [b2_cloud-5] INFO com.github.test.b2_cloud.Main - test.ts SUCCEEDED 100% 64/65
19:57:02.467 [main] INFO com.github.test.b2_cloud.Main - test.ts upload completed -> B2FileVersion{fileId='4_z5ce25d55955797f56a4d0a1a_f207fa310c3ca3ad4_d20180718_m033635_c001_v0001036_t0038', contentLength=6589661884, contentType='application/octet-stream', contentSha1='none', action='upload', uploadTimestamp=1531884995000, fileInfo=[1], fileName='test.ts'}
```

Note that on upload success, the SHA1 field has become `none` though the file content source field was populated with `e8079d27e0bde7eb92eb14f417cb18bdd7b24d6d`.

Bucket lifecycle is set to `Keep only the last version of the file`.

**Comment by certainmagic** [comment]
Hi Adam --

Good question.  Large files do not have SHA-1s for the entire file [1].
When you provide a SHA-1 for a large file upload, the SDK follows the
recommendation of putting your value into the 'large_file_sha1' fileInfo.

Can you check that the value is making it there?

thanks,
ab


[1] "SHA1 Checksums" in https://www.backblaze.com/b2/docs/large_files.html

**Comment by azell** [comment]
I see `File Info: large_file_sha1: e8079d27e0bde7eb92eb14f417cb18bdd7b24d6d` in the UI.  Is there any notes in the SDK to illustrate this use case (specifically not being to rely on the SHA1 field for large files even if passed in explicitly)?

**Comment by certainmagic** [comment]
Hi azell --

I'm soooo sorry I didn't see this earlier...much much earlier.  :(
I left the country for a couple of weeks on July 19th and I
must have lost the email saying you had replied.  And I failed
to notice after that.  That's really embarrassing.

> I see `File Info: large_file_sha1: e8079d27e0bde7eb92eb14f417cb18bdd7b24d6d` in the UI. Are there any notes in the SDK to illustrate this use case (specifically not being to rely on the SHA1 field for large files even if passed in explicitly)?

Not that I know of.  :(

I just added some comments to the content source interface and the builders of the two implementations. It's in https://github.com/Backblaze/b2-sdk-java/pull/55.

ttfn,
ab

**Comment by certainmagic** [comment]
> Is this the correct way to determine if a file exists in the bucket with minimal network traffic? Not setting the prefix appears to return many entries.

Not setting the prefix means to start iterating at the startFileName, so, yes, that will keep listing things as long as you have them.

If you have the bucket's *name*, the easiest way to learn whether it's present or not is to call B2StorageClient.getFileInfoByName().  it will return a B2FileVersion if the file exists, or throw a B2Exception if there's any trouble. If the file doesn't exist, you should get a B2NotFoundException, otherwise it will be some other exception.

An additional benefit of B2StorageClient.getFileInfoByName() is that it's currently implemented by using a HEAD request on the file which means it uses a less expensive transaction type than listFileVersions does.

Please let me know how this goes for you.

again, sorry for the delayed reponse,
ab

**Comment by certainmagic** [comment]
I've merged that PR.

**Comment by azell** [comment]
No worries, I will switch to `B2StorageClient.getFileInfoByName()` in the next couple of days and report back.

**Comment by azell** [comment]
That API call does not appear to be working as expected, as it always throws a `B2NotFoundException` even after a previous upload of the same file has succeeded.

Code:

```
  private boolean exists(String fileName, String sha1) throws B2Exception {
    try {
      var version =
          client.getFileInfoByName(B2GetFileInfoByNameRequest.builder(bucketId, fileName).build());

      // never gets here...
      return fileName.equals(version.getFileName())
          && (sha1.equals(version.getContentSha1())
              || sha1.equals(version.getLargeFileSha1OrNull()));
    } catch (B2NotFoundException e) {
      // only gets here, even if file already exists
      return false;
    }
  }
```

**Comment by certainmagic** [comment]
I’m pretty sure the first argument should be the bucketName not bucketId.

**Comment by azell** [comment]
That appears to be correct, though it does suggest that the SDK could use concrete types other than Strings to represent concepts (names vs. IDs).

**Comment by certainmagic** [comment]
It's true that it'd be more type-safe if ids and names were distinct types.  We'll have to consider that in the future.  It could be fairly disruptive to change it now.
