### ISSUE TITLE
SHA1 on large file upload in b2_start_large_file not sent back

### ISSUE THREAD

**Issue by gcstang** [Backblaze/b2-sdk-java#58]
Version: Latest API available 

I've uploaded a large file and set the SHA1 as defined here:
large_file_sha1 in file info of the [https://www.backblaze.com/b2/docs/b2_start_large_file.html](https://www.backblaze.com/b2/docs/b2_start_large_file.html)

When I try to download the file by name
[https://www.backblaze.com/b2/docs/b2_download_file_by_name.html](https://www.backblaze.com/b2/docs/b2_download_file_by_name.html)
there is a section that say's to pass 'b2ContentDisposition' but I'm not understanding what needs to be passed as the value for that key.  Is there some better documentation on what should be passed or maybe the specific value for what I'm attempting to pull 'large_file_sha1' from file info?

GOAL:
I'd like to validate what I downloaded is what was originally uploaded.

**Comment by certainmagic** [comment]
Hi gcstang --

b2ContentDisposition is a flag that will let you set the http "Content-Disposition" header in the response.  That's unrelated to the SHA1.

B2 does not compute or return a sha1 for a whole large file.  Each part of a large file that you upload separately has its own sha1 set at upload time (and used to verify the contents internally).  The sha1 that you provide to b2-sdk-java at upload time is stored in the 'large_file_sha1' "file info" on the large file and will be returned to you as a file info value when you list files or download the file.

If you want to download the whole large file, you can compare the sha1 you get with the contents of the 'X-Bz-Info-large_file_sha1".

thanks,
ab

**Comment by gcstang** [comment]
> The sha1 that you provide to b2-sdk-java at upload time is stored in the 'large_file_sha1' "file info" on the large file and will be returned to you as a file info value when you list files or download the file.

I've uploaded the value during the b2_start_large_file as fileInfo large_file_sha1 .

> If you want to download the whole large file, you can compare the sha1 you get with the contents of the 'X-Bz-Info-large_file_sha1".

There is no sha1 returned, it's empty when uploaded in the file_info for a multipart upload.
When performing a single file upload and then downloading it, the sha1 is available just not if it was uploaded as a multipart.

**Comment by certainmagic** [comment]
Hi gcstang --

How are you downloading the the large file?  using the SDK or just downloading over HTTP?  

In either case, can you please output the HTTP headers from the download?  The sha1 for a large file should be in the 'X-Bz-Info-large_file_sha1' header.

thanks,
ab

**Comment by gcstang** [comment]
I'm using the API with Go, attached a screenshot of what I get back.

![screen shot 2019-02-05 at 06 47 14](https://user-images.githubusercontent.com/3171369/52274373-1598db00-2912-11e9-8c2c-97e4028db640.png)

**Comment by gcstang** [comment]
Disregard, my fault.
