### ISSUE TITLE
listbuckets with application keys

### ISSUE THREAD

**Issue by tmoliveira** [Backblaze/b2-sdk-java#59]
Hello, 

I am having troubles when trying to list buckets when using an application key restricted to only 1 bucket. The API docs (https://www.backblaze.com/b2/docs/application_keys.html) says that that in this case, i.e., listing a bucket with a specific bucket name using a non-master key will return a list containing this only bucket. However, when I to do that using this java API I am getting errors. Maybe there is something that I am missing.

Test case:
I have already create a B2StorageClient using the application_key_id and and the application_key_secret, and it seems to work as I can upload data to the bucket that this application key have access.

However, for listing buckets we have to specify an 'account id' when creating the B2ListBucketsRequest object. 
When I use my account id (example below) I am getting: 401 -unauthorized.
`B2ListBucketsRequest listBucketsRequest = B2ListBucketsRequest.builder('account id').setBucketName('bubket name').build();`

If I use the application key id instead of the account id I am getting: 400 bad_request: accountId invalid.
`B2ListBucketsRequest listBucketsRequest = B2ListBucketsRequest.builder('application key id').setBucketName('bubket name').build();`

Can you help me on this?

Thanks in advance,
Best regards,
Tiago Oliveira

**Comment by certainmagic** [comment]
Hi Tiago --

You are correct that you want to provide the actual accountId to the builder, as you did in the first example.  As you discovered, using an applicationKeyId there is invalid.

That doesn't explain why your first attempt is giving you an unauthorized error.  What capabilities does your appKey have?  Does it have the listBuckets capability or just the ones related to uploading files?

thanks,
ab

**Comment by tmoliveira** [comment]
Hi,

Thanks for answering.

These are the capabilities my appkey have: deleteFiles, listBuckets, listFiles, readFiles, shareFiles, writeFiles. I believe these are all the capabilities a appkey can have over a bucket, correct? All seems to be set up correctly.

Another question is, once I need the accountId to the list buckets operation, when creating a appkey for a specific user can access a specific bucket, I need to share with this user his appKeyId and appKey, and also my actual accountId. Is this correct?

Thanks,
Tiago Oliveira

**Comment by certainmagic** [comment]
Hi Tiago --

When you authenticate with the B2 API, the server returns a bunch of useful information including the accountId and what you're allowed to do based on the key you authenticated with[1].

Here is a sample account authorization I got with a key similar to the one you described:

```{
  "absoluteMinimumPartSize": 5000000,
  "accountId": "eee2e06894c2",
  "allowed": {
    "bucketId": "2eae3ee26e3016c869640c12",
    "bucketName": "testFavored",
    "capabilities": [
      "listBuckets",
      "listFiles",
      "readFiles",
      "shareFiles",
      "writeFiles",
      "deleteFiles"
    ],
    "namePrefix": null
  },
  "apiUrl": "https://api002.backblazeb2.com",
  "authorizationToken": "....redacted....",
  "downloadUrl": "https://f002.backblazeb2.com",
  "recommendedPartSize": 100000000
}
```

Once you've authenticated with the application's keyId and secret, you can call `client.getAccountId()` to get the account from the response.  You can call `client.getAccountAuthorization().getAllowed()` to get find out what the restrictions are.  From the allowed structure, you can get the bucketName or bucketId that you're restricted to.

Here's a snippet of code that would let you list just the buckets you are allowed to access:

```
final String bucketNameOrNull = client.getAccountAuthorization().getAllowed().bucketName;

// list just the bucket we're allowed to list (or all if not restricted).
bigHeader(writer, "List Buckets");
final B2ListBucketsRequest listRequest = B2ListBucketsRequest
        .builder(client.getAccountId())
        .setBucketName(bucketNameOrNull)
        .build();
for (B2Bucket scan : client.listBuckets(listRequest).getBuckets()) {
    writer.println(" " + scan);
}
```







[1] https://www.backblaze.com/b2/docs/b2_authorize_account.html

**Comment by tmoliveira** [comment]
Hi again,

Thanks for your help. Now it seems to be working correctly. I am not sure why it was not working before as my sample code was almost the same as yours. 

Thanks again,
Regards,
Tiago Oliveira

**Comment by certainmagic** [comment]
I'm glad to hear that it's working for you.  :)

It sounds like you're good now, so I'm going to close this issue.  Please reopen or file new issues as needed.

thanks,
ab
