### ISSUE TITLE
Own implementation of B2ContentWriter

### ISSUE THREAD

**Issue by l0co** [Backblaze/b2-sdk-java#80]
It should be possible to write own `B2ContentWriter` if you want to write downloaded data somewhere else than to memory or file, but currently it isn't because of package-visible constructor.

**Comment by certainmagic** [comment]
Hi --

The intention is that you can implement the B2ContentSink interface to capture the downloaded data in your own way.  B2ContentWriter is just one implementation that has a particular set of options and tradeoffs that seemed reasonable for memory and file downloads.

May I ask where you're planning on writing your data and whether the B2ContentSink meets your needs?

thanks,
ab

**Comment by l0co** [comment]
`B2ContentSink` interface meets my needs, however `B2ContentWriter` seems to provide some common code that I could also adapt, and only provide its abstract methods. Now I needed to write own `B2ContentSink` implementation which partially copies `B2ContentWriter` code (streams copying, exception handling). I'd prefer to extend `B2ContentWriter` instead.

I'm working on streaming data downloaded from B2 directly to the user of my service, so that he can download the data from my service, but in the background it's really downloaded from B2. I want to avoid intermediate data buffering and don't want to save it neither into the memory nor the file, just forward it to  another `PipedOutputStream`.

**Comment by certainmagic** [comment]
Btw, I intentionally didn't make B2ContentWriter subclass-able from outside
the SDK to limit the surface area of the SDK and allow us to make changes
within the SDK without breaking clients.  Of course, B2FileDownloadWriter's
constructor is public, so I might not be achieving my goal.  :) / :(

I think you can do the copying by using B2IoUtils.copy() -- which is
public.  I'm not sure how much of the rest of B2ContentWriter is
interesting for you.  The part where the output is verified by reading it
back in isn't possible since you're forwarding the data to your caller.
Checking the sha1 as it gets to you *might* be interesting to you, although
it won't cover things from end-to-end.  To do end-to-end integrity
checking, it'd be best to pass the sha1 to your caller and let them do the
check.

thoughts?

thanks,
ab

**Comment by l0co** [comment]
OK, I see. I thought this is a mistake with this package-level constructor, but if there's a reason for it you can close this ticket.

About thoughts. Maybe I just personally don't like those many situations where I have code on hand in the lib and I just can't use it because of private, static, finaly, package-level visibility etc :) I like the way micronaut / graphql manages this problem with own `@Internal` annotation pointing that "this is an internal code", and "change it on your own risk", but you still may access, change and use it.

**Comment by certainmagic** [comment]
Thanks, Łukasz.

The @Internal annotation sounds useful.  We may have to try something like that.  For many things, I'd been hoping to eventually use java 9 module stuff to limit what's being exported.

I'll be curious to see how much of B2ContentWriter ends up in your B2ContentSink implementation.

ttfn,
ab

**Comment by l0co** [comment]
Not much. Your implementation does two things: copies streams and calculates+verifies SHA1. I eventually quit checking SHA1 so I use only streams copying. However, if someone wants to write files to whatever storage with SHA1 checking, he currently needs to write both functions once again, while they already exist in your code and are probably well tested.

Although, thinking deeper it maybe is not a problem for the case like this, because in this scenario the user can use the memory writer, and then copy the byte array to it's storage. Depending on how big files he will be downloading...

Maybe the best solution not exposing `B2ContentWriter` as a public API, but giving more flexibility to the user, is to provide third implementation, which writes the data to the `OutputStream` given by the user (`B2ContentOutputStreamWriter`).

**Comment by certainmagic** [comment]
Hi Łukasz --

Thanks for your suggestion regarding B2ContentOutputStreamWriter.

I finally added B2ContentOutputStreamWriter to let people use their own stream source.  See this [commit](https://github.com/Backblaze/b2-sdk-java/commit/7b3488c0af5470516c28a7a2a4c0718312e97774).  By accident, I pushed it directly to master, so it didn't get a PR here in github (but was reviewed internally before I pushed it).  Holler if you've got feedback.

I'm going to close this issue now, but feel free to reopen it if you want.

thanks,
ab

**Comment by l0co** [comment]
@certainmagic I'm really glad this feature is here. However, I work on something different right now. If I need this again, I'm going to use your implementation and give you a feedback.

I'd only provide one more test using `PipedInputStream` and `PipedOutputStream` to check if it works this way and leave it as an example for piping.
